# 服务端口
server:
  port: 8202

spring:
  application:
    # 服务名
    name: service-cmn
  # mysql数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1999-4-i0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    # 环境设置：dev、test、prod
    active: dev

  #redis基本配置
  redis:
    port: 6379
    host: 192.168.6.100
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 20
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0

  #配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
