# 服务端口
server:
  port: 8201

spring:
  application:
    # 服务名
    name: service-hosp
  # mysql数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1999-4-i0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    # 环境设置：dev、test、prod
    active: dev

  data:
    mongodb:
      uri: mongodb://192.168.6.100:27017/yygh

  #配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #rabbitmq地址
  rabbitmq:
    host: 192.168.6.100
    port: 5672
    username: guest
    password: guest

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

